services:
  dms-db-dev:
    image: amazon/dynamodb-local:latest
    container_name: dms-db-dev
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8000'" ]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 2s
    networks:
      proxy-net:

  dms-dev:
    container_name: dms-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FRONTEND_BUILD_MODE: dev
    env_file:
      - .env.dev
    depends_on:
      dms-db-dev:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      proxy-net:


networks:
  proxy-net:
    external: true
